---
# Per environment values which override defaults in hmpps-manage-users-temp-rewrite/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-users-temp-rewrite-stage.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-users-temp-rewrite-stage.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-stage.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-stage.prison.service.justice.gov.uk"
    MANAGE_USERS_API_URL: 'https://manage-users-api-stage.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: STAGE
    AUDIT_ENABLED: "false"
    DPS_ENDPOINT_URL: https://digital-dev.prison.service.justice.gov.uk
    MANAGE_USER_ALLOW_LIST_ENABLED: true
    MANAGE_USER_ALLOW_LIST_ENVIRONMENT_LABEL: stage

generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
